# Generated by Django 3.1.7 on 2021-05-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=1000)),
                ('blood_grp', models.CharField(max_length=3)),
                ('rh', models.CharField(max_length=3)),
                ('image', models.ImageField(upload_to='images/')),
                ('consent', models.BooleanField(default=False)),
            ],
        ),
    ]
